apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: whoami-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whoami-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: whoami-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: whoami-role
  apiGroup: rbac.authorization.k8s.io
